name: 'Create Preview Environment'
description: 'Deploy a Full-Stack Preview Environment (on-demand, ephemeral) with Uffizzi Open Source (Compose + Uffizzi + Kubernetes)'
author: 'Adam Vollrath'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  compose-file:
    description: 'An alternate compose file'
    required: false
    default: 'docker-compose.yaml'
  server:
    description: 'URL to Uffizzi'
    required: false
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: true
  password:
    description: 'Uffizzi password'
    required: true
  project:
    description: 'Uffizzi project name'
    required: true
  ghcr-username:
    description: 'Username to authenticate to GHCR'
    required: false
  ghcr-access-token:
    descrption: 'Password to authenticate to GHCR'
    required: false
outputs:
  url:
    description: 'URL where preview was deployed, if successful'
  id:
    description: 'ID of prevew for later reference'
runs:
  using: 'docker'
  image: 'docker://sergeykirillov/zi_cli:latest'
  args:
    - 'preview'
    - 'create'
    - '--output=github-action'
    - ${{ inputs.compose-file }}
  env:
    UFFIZZI_PASSWORD: ${{ inputs.password }}
    UFFIZZI_SERVER: ${{ inputs.server }}
    UFFIZZI_USER: ${{ inputs.username }}
    UFFIZZI_PROJECT: ${{ inputs.project }}
    GITHUB_USERNAME: ${{ inputs.ghcr-username }}
    GITHUB_ACCESS_TOKEN: ${{ inputs.ghcr-access-token }}
    GITHUB_ACTOR: ${{ github.actor }}
    GITHUB_GITHUB_TOKEN: ${{ github.token }}
